"""initial migration for hasil_kurva_gempa

Revision ID: 7078a33999a3
Revises: 
Create Date: 2025-03-05 16:48:30.028799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7078a33999a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_kurva_gempa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('nilai_y_cr_mmi500', sa.Float(), nullable=True),
    sa.Column('nilai_y_mcf_mmi500', sa.Float(), nullable=True),
    sa.Column('nilai_y_mur_mmi500', sa.Float(), nullable=True),
    sa.Column('nilai_y_cr_mmi250', sa.Float(), nullable=True),
    sa.Column('nilai_y_mcf_mmi250', sa.Float(), nullable=True),
    sa.Column('nilai_y_mur_mmi250', sa.Float(), nullable=True),
    sa.Column('nilai_y_cr_mmi100', sa.Float(), nullable=True),
    sa.Column('nilai_y_mcf_mmi100', sa.Float(), nullable=True),
    sa.Column('nilai_y_mur_mmi100', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('raw_gempa', schema=None) as batch_op:
        batch_op.alter_column('lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_gempa', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('hasil_kurva_gempa')
    # ### end Alembic commands ###
